### ISSUE TITLE
Provide more aspects of the components as part of this addon 

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-learn-search-components#2]
I've implemented these components into the guides-app and I had to copy and paste a whole bunch of stuff from the API application. Here is my initial commit so that we can see what was needed to at least get it working: https://github.com/ember-learn/guides-app/pull/39/commits/9ab2ad6143cf5684255777ec5797f4c6ec2dd2d8

## Tasks
- [x] include html-safe as a helper in this component
	- yes we can discuss the *right* thing to do but I would add that as a follow-on item after the initial release
- [x] Include _search-input.scss in this addon
- [x] consider including a _variables.scss that covers **only** the required variables that this component needs
	- it is potentially likely that we will have these vairables defined in https://github.com/ember-learn/ember-styleguide but I don't know if we might have a "diamond dependency" if both this addon and the consuming app depend on styleguide
- [x] add something to the blueprint that installs "ember-algolia" and "algoliasearch" into the consuming app (see https://github.com/ember-learn/ember-learn-search-components/issues/5)

**Comment by mansona** [comment]
Most of these issues are covered in https://github.com/ember-learn/ember-learn-search-components/pull/4 I will pull the last item into it's own issue

**Comment by jaredgalanis** [comment]
We're closing this because the only repos which consume this tool are archived/deprecated. Thank you for your interest in contributing to the Ember project!
